components:
  securitySchemes:
    accessToken:
      name: access_token
      type: http
      scheme: bearer
      description: |-
        [Contact us](mailto:info@lfca.ngo) in order to get you personal access token.