name: ci
on:
  push:
    branches:
      - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run linter
        run: yarn lint

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    outputs:
      preview_url: ${{ steps.vercel-deploy.outputs.preview-url }}
    steps:
      - uses: actions/checkout@v2
      - name: Determine vercel args
        uses: haya14busa/action-cond@v1
        id: vercel-args
        with:
          cond: ${{ github.ref_name == 'main' }}
          if_true: '--prod'
          if_false: ''
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        id: vercel-deploy
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: ${{ steps.vercel-args.outputs.value }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}